### ISSUE TITLE
how to display coverage report???

### ISSUE THREAD

**Issue by sh977218** [jaydenseric/coverage-node#3]

**Comment by jaydenseric** [comment]
If you are using the `coverage-node` CLI, then after the Node.js script/module has exited it will report in the terminal what files are covered, and if others have ignored or uncovered code locations, it will report those specific locations.

If you are using the JS API, the function [`analyseCoverage`](https://github.com/jaydenseric/coverage-node/blob/v8.0.0/analyseCoverage.mjs) can be used to get the report data, and the function [`reportCoverage`](https://github.com/jaydenseric/coverage-node/blob/v8.0.0/reportCoverage.mjs) can be used to report that data to the console like the CLI does.

Note that this package using V8 code coverage data that Node.js natively produces, so you can always read and report that data manually if you want; read more here:

https://nodejs.org/api/cli.html#node_v8_coveragedir
